version: "3.9"
services:
  www:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: visit_counter
      MARIADB_USER: counter_user
      MARIADB_PASSWORD: password
    volumes:
      - "./db:/docker-entrypoint-initdb.d"